# Generated by Django 4.2.2 on 2023-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
    ]
