# Generated by Django 4.2.2 on 2023-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
