# Generated by Django 4.2.2 on 2023-06-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DairyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memb_fname', models.CharField(max_length=10)),
                ('memb_lname', models.CharField(max_length=10)),
                ('memb_fullname', models.CharField(max_length=10)),
                ('memb_age', models.IntegerField()),
                ('memb_address', models.CharField(max_length=10)),
                ('memb_image', models.ImageField(upload_to='membimage')),
            ],
        ),
    ]
